# Generated by Django 4.1.3 on 2022-11-25 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginModel',
        ),
        migrations.RenameField(
            model_name='registermodel',
            old_name='Mobile',
            new_name='mobile',
        ),
    ]
